module.exports = {
  명사: 'noun',
  대명사: 'pronoun',
  수사: 'numeral',
  조사: 'postposition',
  동사: 'verb',
  형용사: 'adjective',
  관형사: 'determiner',
  부사: 'adverb',
  감탄사: 'exclamation',
  접사: 'affix',
  의존: 'dependent',
  '의존 명사': 'dependent noun',
  '보조 동사': 'helper verb',
  '보조 형용사': 'helper adjective',
  어미: 'ending',
  '품사 없음': 'N/A',
};
